# Generated by Django 5.2 on 2025-05-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('C', 'Client'), ('O', 'Organisateur'), ('A', 'Administrateur')], default='C', max_length=1),
        ),
    ]
